import {BlitzProvider} from "./blitz-client"

export const metadata = {
  title: { default: "OCX Loader Toolkit", template: "%s – Blitz" },
  description: "Generated by blitz new",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <BlitzProvider>
          <>{children}</>
        </BlitzProvider>
      </body>
    </html>
  )
}

